highlighter: rouge
#markdown: rdiscount
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://bhikadia.com/resume
author: FÃ¡bio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Harsh Bhikadia's Resume
name: Harsh Bhikadia
email: harsh@bhikadia.com
email_full: mailto:harsh@bhikadia.com
website: bhikadia.com
website_full: https://bhikadia.com
github: daadu
twitter: 4not7
tel: +91 9158 997751
tel_full: tel:+919158997751
google_maps: 'https://www.google.co.in/maps/place/NMIMS+Shirpur+Campus+Boys+Hostel,+Shirpur,+Maharashtra+425405/@21.2862652,74.8396147,17z'
address: 158, Boys Hostel, Mukesh Patel School of Technology Management & Engineering
postcode: 425 405
city: Shirpur
country: India
google_analytics: UA-71475870-2

# needed for travis-ci build
exclude: [vendor]
